"""The question bank behind quiz.py -- one card per idiom in CHEATSHEET.md.

Each card gives you a hint (what you are trying to do, in words) and holds the
answer (how you write it). The quiz never compares your text to the answer: it
shows you both and you decide whether you had it. That is deliberate -- there
are five correct ways to write most of these, and no comparison would judge
them fairly.

Every answer is copied verbatim from CHEATSHEET.md, and test_quiz.py checks
that it stayed that way. If you edit the cheatsheet, run the test.

You do not need to understand this file to use the quiz. Come back to it after
step 10 if you are curious -- it is a list of dataclasses, nothing more.
"""

from dataclasses import dataclass


@dataclass
class Card:
    """One thing worth being able to write without looking it up."""

    section: int      # 1-11, matching the headings in CHEATSHEET.md
    hint: str         # the intent, in plain words
    answer: str       # the form, verbatim from the cheatsheet
    note: str = ""    # the trap, or the reason, shown with the answer


SECTIONS = {
    1: "Values, variables, f-strings",
    2: "Conditionals",
    3: "Loops",
    4: "Strings",
    5: "Lists and tuples",
    6: "Dicts and sets",
    7: "Functions",
    8: "Comprehensions and friends",
    9: "Errors and files",
    10: "Classes",
    11: "Errors worth recognising on sight",
}

# Section 11 answers are prose, not code -- the quiz turns off syntax
# highlighting for them.
PROSE_SECTION = 11


CARDS = [
    # --- 1 -- Values, variables, f-strings -----------------------------------
    Card(1, "store a true/false value",
         "is_student = True",
         "capitalised -- True and False, not true and false"),
    Card(1, "put a name inside a sentence",
         'f"Hello, {name}!"',
         "the f goes before the opening quote; the expression goes inside {}"),
    Card(1, "show a float with exactly two decimal places",
         'f"{height:.2f}"'),
    Card(1, "do arithmetic inside a formatted string",
         'f"{age + 1}"',
         "any expression works in there, not just a bare name"),
    Card(1, "turn the text 42 into a whole number",
         'int("42")'),
    Card(1, "turn the text 3.5 into a decimal number",
         'float("3.5")'),
    Card(1, "turn the number 42 into text",
         "str(42)"),
    Card(1, "ask what type a value is, as a plain word",
         "type(age).__name__",
         'gives "int", not the noisier <class \'int\'>'),
    Card(1, "exchange two variables' values without a temporary",
         "a, b = b, a"),

    # --- 2 -- Conditionals ---------------------------------------------------
    Card(2, "run a block only when something is true",
         "if condition:"),
    Card(2, "try a second condition, but only if the first one failed",
         "elif other:",
         "checked only if the ones above failed"),
    Card(2, "the block that runs when nothing above matched",
         "else:"),
    Card(2, "the six ways to compare two values",
         "==  !=  <  <=  >  >=",
         "== compares, = assigns -- the single most common typo"),
    Card(2, "combine or negate conditions",
         "and  or  not"),
    Card(2, "choose between two values in one expression",
         'x = "one" if n == 1 else "many"',
         "a conditional expression -- the value comes first, then the test"),
    Card(2, "every value Python treats as false",
         'False   None   0   0.0   ""   []   {}   ()   set()',
         "everything else is true, including -1 and \"0\""),

    # --- 3 -- Loops ----------------------------------------------------------
    Card(3, "visit every item of a sequence in turn",
         "for item in sequence:"),
    Card(3, "count 0, 1, 2, 3, 4",
         "for i in range(5):",
         "stop is EXCLUSIVE -- range(5) never yields 5"),
    Card(3, "count 1, 2, 3, 4, 5",
         "for i in range(1, 6):"),
    Card(3, "count 0, 2, 4, 6, 8",
         "for i in range(0, 10, 2):",
         "the third argument is the step"),
    Card(3, "count down 5, 4, 3, 2, 1",
         "for i in range(5, 0, -1):"),
    Card(3, "repeat for as long as something stays true",
         "while condition:",
         "something in the body must change the condition, or it never ends"),
    Card(3, "leave the loop entirely",
         "break"),
    Card(3, "abandon this item and move to the next",
         "continue"),
    Card(3, "add up every number in a list",
         "total = 0\nfor n in numbers:\n    total += n\nreturn total",
         "the accumulator -- the shape behind half of all loops"),

    # --- 4 -- Strings --------------------------------------------------------
    Card(4, "the first character",
         "s[0]"),
    Card(4, "the last character, without knowing the length",
         "s[-1]"),
    Card(4, "characters 1, 2 and 3",
         "s[1:4]",
         "the stop index is excluded, exactly like range"),
    Card(4, "the first three characters",
         "s[:3]"),
    Card(4, "everything from index 3 to the end",
         "s[3:]"),
    Card(4, "the string backwards",
         "s[::-1]"),
    Card(4, "how many characters it has",
         "len(s)"),
    Card(4, "the same text in lower case",
         "s.lower()"),
    Card(4, "the same text in upper case",
         "s.upper()",
         "returns a NEW string -- s itself is unchanged. Strings are immutable"),
    Card(4, "remove the whitespace at both ends",
         "s.strip()"),
    Card(4, "the first letter capitalised, the rest lower",
         "s.capitalize()"),
    Card(4, "cut a string into a list on every comma",
         's.split(",")'),
    Card(4, "cut a string on any run of whitespace",
         "s.split()",
         "no argument means: split on any whitespace, and drop the empties"),
    Card(4, "glue a list of strings together with commas",
         '",".join(parts)',
         "the inverse of split -- the separator goes in front"),
    Card(4, "swap every occurrence of one substring for another",
         "s.replace(old, new)"),
    Card(4, "test whether a string begins with a given prefix",
         "s.startswith(p)"),
    Card(4, 'test whether "th" appears anywhere in it',
         '"th" in s'),

    # --- 5 -- Lists and tuples -----------------------------------------------
    Card(5, "a sequence you can change afterwards",
         'items = ["a", "b"]'),
    Card(5, "a pair that must stay fixed",
         "point = (3, 4)"),
    Card(5, "a tuple holding a single value",
         "(5,)",
         "the COMMA makes it a tuple, not the brackets: (5,) not (5)"),
    Card(5, "add one item at the end",
         "items.append(x)"),
    Card(5, "put an item at a chosen position",
         "items.insert(i, x)"),
    Card(5, "delete the first item equal to some value",
         "items.remove(value)"),
    Card(5, "take the last item off and hand it back",
         "items.pop()"),
    Card(5, "sort a list where it stands",
         "items.sort()",
         "in place, returns None -- items = items.sort() destroys your list"),
    Card(5, "get a sorted copy, leaving the original alone",
         "sorted(items)",
         "a NEW list"),
    Card(5, "copy a list",
         "items[:]",
         "or list(items) -- both give you a new list, not another name for it"),
    Card(5, "join two lists into one",
         "items + other"),
    Card(5, "a list of three zeros",
         "[0] * 3"),
    Card(5, "pull a pair apart into two names",
         "x, y = point",
         "unpacking"),
    Card(5, "take the first item and everything after it, in one line",
         "head, *tail = items",
         "star-unpacking -- tail is always a list, even when empty"),

    # --- 6 -- Dicts and sets -------------------------------------------------
    Card(6, "a lookup table from names to numbers",
         'ages = {"ada": 36}'),
    Card(6, "read a key, and blow up if it is missing",
         'ages["ada"]',
         "KeyError if absent"),
    Card(6, "read a key, falling back to 0 when it is missing",
         'ages.get("bob", 0)'),
    Card(6, "add a key, or overwrite it",
         'ages["bob"] = 27'),
    Card(6, "remove a key",
         'del ages["bob"]'),
    Card(6, "test whether a key is present",
         '"ada" in ages'),
    Card(6, "loop over a dict",
         "for k in ages:",
         "plain iteration hands you the KEYS, not the values"),
    Card(6, "loop over keys and values together",
         "for k, v in ages.items()"),
    Card(6, "loop over the values only",
         "for v in ages.values()"),
    Card(6, "a collection where every item is unique",
         'seen = {"a", "b"}'),
    Card(6, "an empty set",
         "empty = set()",
         "NOT {} -- that is an empty dict"),
    Card(6, "add something to a set",
         "seen.add(x)"),
    Card(6, "everything that is in either set",
         "a | b",
         "union"),
    Card(6, "only what appears in both sets",
         "a & b",
         "intersection"),
    Card(6, "what is in the first set but not the second",
         "a - b",
         "difference"),
    Card(6, "count how often each word appears",
         "counts[word] = counts.get(word, 0) + 1",
         "the counting idiom -- get() supplies the 0 for a word never seen"),

    # --- 7 -- Functions ------------------------------------------------------
    Card(7, "define a function whose second argument has a default of 2",
         'def power(base, exp=2):\n    """Docstring."""\n    return base ** exp',
         "arguments with defaults come last"),
    Card(7, "call it, letting the default stand",
         "power(3)"),
    Card(7, "call it naming both arguments",
         "power(base=3, exp=3)",
         "keyword arguments can come in any order"),
    Card(7, "accept any number of positional arguments",
         "def total(*nums):",
         "they arrive as a TUPLE"),
    Card(7, "accept any number of keyword arguments",
         "def describe(**kwargs):",
         "they arrive as a DICT"),
    Card(7, "keep a function in a variable",
         "f = power",
         "a function is a value; f(4) then calls it. No brackets when storing"),
    Card(7, "give an argument an empty list as its default, safely",
         "def add(item, target=None):\n    if target is None:\n        target = []",
         "never use a mutable default -- one list would be shared by every call"),
    Card(7, "a function that remembers a count between calls",
         "def make_counter():\n    count = 0\n    def step():\n        nonlocal count\n        count += 1\n        return count\n    return step",
         "a closure -- step keeps hold of count after make_counter has returned"),
    Card(7, "assign to a name that belongs to the enclosing function",
         "nonlocal count",
         "without it, count += 1 raises UnboundLocalError"),

    # --- 8 -- Comprehensions and friends -------------------------------------
    Card(8, "build a new list out of every item of another",
         "[expr for item in seq]"),
    Card(8, "build a list from only the items that pass a test",
         "[expr for item in seq if condition]",
         "the if goes at the end"),
    Card(8, "build a dict in one expression",
         "{k: v for item in seq}"),
    Card(8, "build a set in one expression",
         "{expr for item in seq}"),
    Card(8, "produce the items lazily, one at a time",
         "(expr for item in seq)",
         "a generator -- nothing is computed until you iterate over it"),
    Card(8, "walk a sequence with a running index",
         "enumerate(seq)"),
    Card(8, "walk it with the index starting at 1",
         "enumerate(seq, start=1)"),
    Card(8, "walk two sequences side by side",
         "zip(a, b)",
         "stops at the shortest. Lazy -- wrap in list(...) to keep it"),
    Card(8, "sort longest first",
         "sorted(seq, key=len, reverse=True)"),
    Card(8, "sort a dict's pairs by their value",
         "sorted(d.items(), key=lambda kv: kv[1])",
         "kv is the (key, value) pair; kv[1] is the value"),
    Card(8, "a nameless one-expression function that doubles its argument",
         "lambda x: x * 2"),

    # --- 9 -- Errors and files -----------------------------------------------
    Card(9, "attempt something, catching one specific failure",
         "try:\n    risky()\nexcept ValueError as err:\n    ...",
         "name what you expect; never a bare except:"),
    Card(9, "the try branch that runs only when nothing went wrong",
         "else:",
         "ran without an exception"),
    Card(9, "the branch that runs whether or not it blew up",
         "finally:",
         "always -- this is where cleanup goes"),
    Card(9, "signal an error yourself, with a useful message",
         'raise ValueError(f"expected a positive number, got {n}")',
         "say what you expected and what you got"),
    Card(9, "open a file so that it closes itself",
         "with open(path) as f:",
         "closes itself, even on an exception"),
    Card(9, "read the whole file into one string",
         "text = f.read()"),
    Card(9, "read the lines with their newlines stripped off",
         'lines = [line.rstrip("\\n") for line in f]'),
    Card(9, "open a file for writing",
         'with open(path, "w") as f:',
         '"w" truncates the file, "a" appends to it'),
    Card(9, "write one line to it",
         'f.write(line + "\\n")',
         "write() adds no newline of its own"),
    Card(9, "import the modern way of handling paths",
         "from pathlib import Path"),
    Card(9, "ask whether a file exists",
         'Path("f.txt").exists()'),

    # --- 10 -- Classes -------------------------------------------------------
    Card(10, "define a class",
         "class Rectangle:"),
    Card(10, "the method that runs when the object is built",
         "def __init__(self, width, height):\n    self.width = width\n    self.height = height",
         "runs on Rectangle(...); assigning to self.x is what makes an attribute"),
    Card(10, "a method that computes something from the object's own data",
         "def area(self):\n    return self.width * self.height",
         "every method takes self first"),
    Card(10, "control how the object shows up when printed",
         "def __repr__(self):\n    return f\"Rectangle(width={self.width}, height={self.height})\"",
         "aim for something you could paste back into Python"),
    Card(10, "build one",
         "r = Rectangle(3, 4)"),
    Card(10, "read one of its attributes",
         "r.width",
         "an attribute -- no brackets"),
    Card(10, "call one of its methods",
         "r.area()",
         "a method -- it needs the brackets"),
    Card(10, "get __init__, __repr__ and __eq__ written for you",
         "from dataclasses import dataclass\n\n@dataclass\nclass Point:\n    x: int\n    y: int"),
    Card(10, "make len(obj) work on your own class",
         "__len__"),
    Card(10, "make == compare two of your objects by their contents",
         "__eq__"),

    # --- 11 -- The errors worth recognising on sight -------------------------
    # Hint is the message Python printed; answer is what you did to earn it.
    Card(11, "NameError: name 'x' is not defined",
         "Typo, or used before assigning"),
    Card(11, 'TypeError: can only concatenate str (not "int") to str',
         '"a" + 1 — use an f-string'),
    Card(11, "IndentationError: expected an indented block",
         "Forgot to indent after a :"),
    Card(11, "IndexError: list index out of range",
         "Off-by-one; len(x) is one past the end"),
    Card(11, "KeyError: 'bob'",
         "Missing dict key — use .get()"),
    Card(11, "ValueError: invalid literal for int()",
         'int("abc")'),
    Card(11, "AttributeError: 'NoneType' object has no attribute ...",
         "You assigned the result of an in-place method"),
    Card(11, "UnboundLocalError",
         "Assigned to a name you also read from an outer scope — needs nonlocal"),
    Card(11, "TypeError: 'zip' object is not subscriptable",
         "It is lazy — wrap in list()"),
    Card(11, "FileNotFoundError",
         "Wrong path, or relative to the wrong directory"),
]
